### ISSUE TITLE
Touch scrolling doesn´t work at all in chrome nor opera!!!

### ISSUE THREAD

**Issue by andres770105** [creativetimofficial/ct-material-dashboard-pro#77]
This is a major bug because of the responsive requirements. Touch scrolling doesn't work even in your material dashboard pro live demo (v1.2.0), when viewed in chrome (tested with chrome v61.0.3163.100) and Opera (v48.0.2685.52).

**Comment by andres770105** [comment]
I recently tried to update the perfect plugin-scrollbar.jquery.min.js from v0.6.13 to v0.8.1 and it seems that the problem has been solved, however, no exhaustive tests has been made yet to the whole framework.

**Comment by alexandru-paduraru** [comment]
@andres770105 thank you for the information. Can you please let us know what devices you used? We would like to replicate that and if the issue is from PS or from our CSS. Even if it is working with v0.8.1 we want to do more tests.

Best,
Alex

**Comment by andres770105** [comment]
I used a Sony VAIO DUO 13 with touch screen (1920x1080 dpi resolution), with Windows 10 Pro (fully updated version). I tested my website and your Material Dashboard Live Demo in Chrome (v61 and v62), Opera (v48), Microsoft Edge (v40.15), Firefox (v56). It works only on Edge and Firefox, while in Chrome and Opera the touch capabilities doesn't work.

I tested also in Chrome for android (v61.0.31) on my Samsung Galaxy S7 Edge running Android 7.0.0 and yes, it works there.

So, I updated the Perfect-scrollbar plugin to 0.8.1 and now its working in all devices.

Touch capability is crucial to my website POS touch system, wich is primary used in windows touch pcs by many stores in Colombia.

I hope this information can help.

**Comment by khrystyan88** [comment]
Uncaught TypeError: t.msMatchesSelector is not a function

**Comment by khrystyan88** [comment]
The scroll works if I scroll in the dashboard but it stops working when it reaches the normal state.

**Comment by khrystyan88** [comment]
today the file demo.js that I had of the other version changed and the scrollbar has started to work, I will comment if another error appears
